#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH="~/bin:/Users/jodi/.homebrew/bin:~/.homebrew/Library/LinkedKegs/coreutils/libexec/gnubin:$PATH"

pathdirs=(
    ~/.bin
    /Users/jodi/.bin/flip
    /Users/jodi/.rbenv/versions/2.2.3/bin
    ~/.rbenv/shims
    /usr/local/bin
    ~/.composer/vendor/bin
)
for dir in $pathdirs; do
    if [ -d $dir ]; then
        path+=$dir
    fi
done

eval "$(rbenv init -)"

. `brew --prefix`/etc/profile.d/z.sh

export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
