#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH="~/bin:/Users/jodi/.homebrew/bin:~/.homebrew/Library/LinkedKegs/coreutils/libexec/gnubin:$PATH"

pathdirs=(
    /usr/local/Cellar/php55/5.5.20/bin
    /Applications/MAMP/bin/php/php5.5.3/bin
    ~/.rbenv/shims
    /usr/local/bin
    ~/.composer/vendor/bin
    /Applications/MAMP/Library/bin
)
for dir in $pathdirs; do
    if [ -d $dir ]; then
        path+=$dir
    fi
done

eval "$(rbenv init -)"

. `brew --prefix`/etc/profile.d/z.sh